# .streamlit/secrets.toml

[supabase]
SUPABASE_URL = "https://lpejnyncbwqhycequiwk.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxwZWpueW5jYndxaHljZXF1aXdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNTMyNDgsImV4cCI6MjA3MTkyOTI0OH0.XSi-mDHccMgpgXUGVsX4euJvum_7Ixj0cGivBweeg9w"